task:
  title: What type of post is this?
dataset:
  directory: dataset/hacker_news/
  data_type: text
  judgements_file: outputs/hacker_news/labels.csv
label:
  type: classification
  classes:
    - News
    - Technology
    - Other
model:
    directory: outputs/hacker_news/models/
user: chris
