task:
  title: Is this text positive?
dataset:
  directory: dataset/text_classification/
  data_type: text
  judgements_file: outputs/text_classification/labels.csv
label:
  type: binary
model:
  directory: outputs/text_classification/models/
user: chris
